environment:
  global:
    CHANNELS: "-c pyviz/label/dev"
  matrix:
    - PY: "2.7"
      CONDA: "C:\\Miniconda-x64"
    - PY: "3.6"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda install -y -c pyviz/label/dev pyctdev && doit ecosystem_setup"
  - "doit env_create %CHANNELS% --name=test --python=%PY%"
  - "activate test"
  - "doit develop_install %CHANNELS%"
  - "doit env_capture"

build: off

test_script:
  - "doit test_all"
