environment:
  global:
    CHANNELS: "-c conda-forge -c pyviz/label/dev"
  matrix:
    - PY: "2.7"
      CONDA: "C:\\Miniconda-x64"
    - PY: "3.6"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda install -y -c pyviz pyctdev && doit ecosystem_setup"
  - "doit env_create %CHANNELS% --name=test --python=%PY%"
  - "activate test"
  - "doit develop_install %CHANNELS%"
  # Fix for https://github.com/conda-forge/pytest-benchmark-feedstock/issues/6
  - "pip install pytest-benchmark --ignore-installed"
  - "doit env_capture"

build: off

test_script:
  - "doit test_all"
  - "set NUMBA_DISABLE_JIT=1 && doit test_unit_nojit & set NUMBA_DISABLE_JIT="
