environment:
  global:
    CHANNELS: "-c pyviz/label/dev -c conda-forge"
  matrix:
    - PY: "2.7"
      PYTHON: "C:\\Python27-x64"
      CONDA: "C:\\Miniconda-x64"
    - PY: "3.6"
      PYTHON: "C:\\Python36-x64"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda install -y -c pyviz/label/dev pyct && doit ecosystem_setup"
  - "doit env_create --name=test --python=%PY%"
  - "conda activate test"
  - "doit develop_install %CHANNELS%"
  - "doit env_capture"

build: off

test_script:
  - "doit test_all_quick"
