name: datashader-docs
channels:
    - bokeh
dependencies:
    - python
    - numpydoc
    - dask >=0.7.6
    - datashape >=0.5.1
    - numba >=0.24.0
    - numpy >=1.7
    - pandas >=0.15.0
    - pillow >=3.1.1
    - xarray >=0.7.0
    - toolz >=0.7.4
